### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by kishorepv** [mit-han-lab/neurips-micronet#2]
Hi,

The link to the data says the files are deleted. Is it possible to share your trained model weights?

Thanks

**Comment by ZhongxiaYan** [comment]
What link are you referring to? Does this Dropbox link (as mentioned in the Readme) not work for you? https://www.dropbox.com/sh/8b37zkfvuyog4tu/AAB1wH9GgQgVgO1b7Lh0Pap4a?dl=0

**Comment by kishorepv** [comment]
It is working. Sorry, I was using a wrong link earlier. Thanks!
