### ISSUE TITLE
Question about transformer structure that it used to challenge

### ISSUE THREAD

**Issue by DongChanS** [mit-han-lab/neurips-micronet#3]
Hi!

I am following your github instruction for using lightweight language modeling.

In the [your report](https://github.com/mit-han-lab/neurips-micronet/blob/master/neurips_micronet_challenge/report.pdf), this statement is written.
> To maintain a fixed context size for predicting each token, the vanilla transformer requires full forward-computation
of the entire context due to its absolute positional embedding, while the Transformer-XL
merely needs to compute the forward-computation for one token due to its **relative positional embeddings**. We note this computational advantage of the Transformer-XL and
incorporate it into our model.

But, in your [source code](https://github.com/mit-han-lab/neurips-micronet/blob/master/model.py#L6), the model seems to be transformer with **absolute positional embedding**.
Even, this positional embedding is trained as parameter.

Then, i have 2 questions.

1. Why you use absolute positional embedding?
2. Why you train positional embedding?

Thank you!

**Comment by ZhongxiaYan** [comment]
Hey

1) It's not an absolute position embedding, it's a relative position embedding. See here for where it's used: https://github.com/mit-han-lab/neurips-micronet/blob/a85bd0ed719b5d6f45642d71f5b83a8eed916025/model.py#L57 . We do some tensor manipulations for this (e.g. notice the .unfold on https://github.com/mit-han-lab/neurips-micronet/blob/a85bd0ed719b5d6f45642d71f5b83a8eed916025/model.py#L54)
2) Trained positional embeddings are also common practice. e.g. look for "learned positional embeddings" in Attention is All You need
